apiVersion: install.karmada.io/v1alpha1
kind: KarmadaDeployment
metadata:
  name: demo-kd
spec:
  mode: Helm
  controlPlane:
    namespace: karmada-system
    endPointCfg:
      secretRef:
        namespace: default
        name: karmada-install
    etcd:
      storageMode: hostPath
    modules:
      - name: scheduler
        replicas: 2
      - name: agent
        replicas: 2
        image: swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-agent:latest
    components:
      - search
      - descheduler
  images:
    karmadaRegistry: swr.ap-southeast-1.myhuaweicloud.com
    karmadaVersion: latest
    kubeResgistry: k8s.gcr.io
    kubeVersion: "v1.24.2"
