name: Build kubectl & cfssl image

env:
  REGISTER: ghcr.io
  IMAGE_REPO: ${{ github.repository }}
  IMAGE_ROOT_PATH: docker
  BUILD_PLATFORM: linux/amd64,linux/arm64
  KUBECTL_VERSION: v1.25.3
  CFSSL_VERSION: v1.6.3
  REGISTER_USER: ${{ github.actor }}
  REGISTER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  # REGISTER: ${{ secrets.REGISTRY_NAME }}
  # REGISTER_USER: ${{ secrets.REGISTRY_USER }}
  # REGISTER_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Login to GitLab
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTER }}
        username: ${{ env.REGISTER_USER }}
        password: ${{ env.REGISTER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.0.0
      with:
        driver-opts: image=moby/buildkit:master

    - name: Build & Pushing kubectl image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.IMAGE_ROOT_PATH }}/kubectl/Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: ${{ env.BUILD_PLATFORM }}
        build-args: |
          KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
        tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/kubectl:${{ env.KUBECTL_VERSION }}
        push: true
        github-token: ${{ env.REGISTER_PASSWORD }}
      
    - name: Build & Pushing cfssl image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ env.IMAGE_ROOT_PATH }}/cfssl/Dockerfile
        labels: |-
          org.opencontainers.image.source=https://github.com/${{ env.IMAGE_REPO }}
          org.opencontainers.image.revision=${{ github.sha }}
        platforms: ${{ env.BUILD_PLATFORM }}
        tags: ${{ env.REGISTER }}/${{ env.IMAGE_REPO }}/cfssl:${{ env.CFSSL_VERSION }}
        push: true
        github-token: ${{ env.REGISTER_PASSWORD }}
