name: Build & Release Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Login registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_RELEASE_NAME }} -u ${{ secrets.REGISTRY_USER }} --password-stdin
      - name: Make and push
        run: |
          make push-multi-architecture-images

